# Generated by Django 3.2.9 on 2022-03-21 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_user', '0003_email_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='main_user',
            name='status',
            field=models.CharField(choices=[('Bloklangan', 'Bloklangan'), ('Bloklanmagan', 'Bloklanmagan')], default='Bloklanmagan', max_length=30),
            preserve_default=False,
        ),
    ]
