# Generated by Django 3.2.9 on 2022-03-23 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_user', '0004_main_user_status'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.FileField(upload_to='mahsulot/')),
                ('verify', models.CharField(default='verify', max_length=30)),
                ('cost', models.IntegerField()),
                ('more', models.TextField()),
                ('aksiya', models.PositiveSmallIntegerField(default=0)),
                ('brand', models.CharField(max_length=80)),
                ('garant', models.CharField(max_length=50)),
                ('delivery_time', models.CharField(max_length=50)),
                ('there', models.BooleanField(default=True)),
                ('inside_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inside_category_wishlist', to='main.category2')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base_user.main_user')),
            ],
        ),
    ]
