# Generated by Django 4.0.3 on 2022-03-26 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_user', '0004_main_user_status'),
        ('main', '0002_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='aksiya',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='delivery_time',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='garant',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='inside_category',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='more',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='name',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='there',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='verify',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.tovar'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_user.main_user'),
        ),
    ]
