# Generated by Django 3.2.9 on 2022-06-03 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_shopping'),
    ]

    operations = [
        migrations.AddField(
            model_name='tovar',
            name='barcode',
            field=models.ImageField(blank=True, upload_to='barcode/'),
        ),
    ]
